name: "Build"

on: [push]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    # Checkout the repository to the GitHub Actions runner
    steps:
      - name: Checkout
        uses: actions/checkout@v2

        # On push to main
      - name: Docker build and push
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: ./build.sh
